In [1]:
#python program to demonstrate basic array characteristics
import numpy as np

In [2]:
#creating array object
arr = np.array([[1,2,3],
              [4,2,5]])
print("Array is of type: ",type(arr))

Array is of type:  <class 'numpy.ndarray'>


In [3]:
print("No of dimensions: ",arr.ndim)

No of dimensions:  2


In [4]:
print("Shape of the array: ",arr.shape)

Shape of the array:  (2, 3)


In [5]:
print("Size of the array: ",arr.size)

Size of the array:  6


In [6]:
print("Array stores elements of type: ",arr.dtype)

Array stores elements of type:  int32


# Array creation techniques

In [11]:
#creating array from list with type float
a = np.array([[1,2,4],[5,8,7]], dtype='float')
print("Array created using passed list: \n",a)

Array created using passed list: 
 [[1. 2. 4.]
 [5. 8. 7.]]


In [12]:
#creating array from tuple
b = np.array((1,3,2))
print("\nArray created using passing tuple: \n",b)


Array created using passing tuple: 
 [1 3 2]


In [13]:
#creating 3*4 array with all zeros
c = np.zeros((3,4))
print("\nArray initialized with all zeros: \n",c)



Array initialized with all zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
#create a constant value array of complex type
d = np.full((3,3),6, dtype='complex')
print("\nArray initialized with all sixes: \n",d)


Array initialized with all sixes: 
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [15]:
#create an array with random values
e=np.random.random((2,2))
print("Random array \n ",e)

Random array 
  [[0.67317175 0.53432599]
 [0.46076623 0.02958153]]


In [16]:
#create a sequence of integers from 0 to 30 with step=5
f=np.arange(0,30,5)
print("Sequntial array with steps of 5:\n",f)

Sequntial array with steps of 5:
 [ 0  5 10 15 20 25]


In [19]:
#create a sequnce of 10 values in range 0 to 5
g=np.linspace(0,5,10)
print("Sequntial array with 10 values between 0 and 5\n",g)

Sequntial array with 10 values between 0 and 5
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [20]:
#Reshaping 3x4 array to 2x3x3 array
arr=np.array([[1,2,3,4],
             [5,2,4,2],
             [1,2,0,1]])
newarr=arr.reshape(2,2,3)
print("Original array:\n",arr)
print("Reshaped array:\n",newarr)

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [21]:
#Flatten array
arr=np.array([[1,2,3],[4,5,6]])
flarr=arr.flatten()
print("Original array:\n",arr)
print("Flattened array is:\n",flarr)

Original array:
 [[1 2 3]
 [4 5 6]]
Flattened array is:
 [1 2 3 4 5 6]


In [22]:
#prgm for indexing in numpy
arr=np.array([[-1,2,0,4],
             [4,-0.5,6,0],
             [2.6,0,7,8],
             [3,-7,4,2.0]])

In [23]:
#slicing array
temp=arr[:2, ::2]
print("Array with first 2 rows and alternate columns(0 and 2):\n",temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [25]:
#integer array indexing
temp=arr[[0,1,2,3,],[3,2,1,0]]
print("Elements at indices (0,3),(1,2),(2,1)\n",temp)

Elements at indices (0,3),(1,2),(2,1)
 [4. 6. 0. 3.]


In [26]:
#boolean array indexing
cond=arr>0 #cond is a boolean array
temp = arr[cond]
print("Elements greater than 0\n",temp)

Elements greater than 0
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [27]:
#basic operations on single array
a=np.array([1,2,5,3])


In [28]:
#add 1 to every element
print("Adding 1 to every element:",a+1)

Adding 1 to every element: [2 3 6 4]


In [29]:
print("Subtracting 3 from each element:",a-3)

Subtracting 3 from each element: [-2 -1  2  0]


In [30]:
print("Multiplying each element by 10",a*10)

Multiplying each element by 10 [10 20 50 30]


In [31]:
print("Sqaring each element:",a**2)

Sqaring each element: [ 1  4 25  9]


In [32]:
#modify existing array
a *=2
print("Doubled each element of array:",a)

Doubled each element of array: [ 2  4 10  6]


In [33]:
#transpose of array
a=np.array([[1,2,3],[3,4,5],[9,6,0]])
print("Original array:\n",a)
print("Transpose of array:\n",a.T)

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [34]:
#unary operations in numpy
arr=np.array([[1,5,6],[4,7,2],[3,1,9]])

In [35]:
print("Largest element is:",arr.max())

Largest element is: 9


In [37]:
print("Row-wise maximum elements:",arr.max(axis=1))

Row-wise maximum elements: [6 7 9]


In [38]:
print("Minimum element of array:",arr.min())

Minimum element of array: 1


In [39]:
print("Sum of all array elements:",arr.sum())

Sum of all array elements: 38


In [40]:
print("cumilative sum along each row:\n",arr.cumsum(axis=1))

cumilative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [41]:
#binary operations in Numpy
a=np.array([[1,2],
           [3,4]])
b=np.array([[4,3],
           [2,1]])


In [42]:
print("Array sum:\n",a+b)

Array sum:
 [[5 5]
 [5 5]]


In [43]:
print("Array multiplication:\n",a*b)

Array multiplication:
 [[4 6]
 [6 4]]


In [45]:
print("Matrix multiplication:\n",a.dot(b))

Matrix multiplication:
 [[ 8  5]
 [20 13]]


# Universal functions in Numpy

In [46]:
#create an array of sine values
a=np.array([0,np.pi/2,np.pi])
print("Sine values of array elements:",np.sin(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [47]:
#Exponential values
a=np.array([0,1,2,3])
print("Exponent of array elements:",np.exp(a))

Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]


In [48]:
print("Square root of array elements:",np.sqrt(a))

Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [49]:
#sorting
a=np.array([[1,4,2],
           [3,4,6],
           [0,-1,5]])

In [50]:
print("Array elements in sorted order:\n",np.sort(a,axis=None))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]


In [51]:
print("Row-wise sorted array:\n",np.sort(a,axis=1))

Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [52]:
#specify sort algorithm
print("Column wise sort by applying merge-sort:\n",np.sort(a,axis=0,kind='mergesort'))

Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [53]:
#sorting of structured array
#set alias name for dtypes
dtypes = [('name','S10'),('grad_year',int),('cgpa',float)]

In [54]:
#values to be put in array
values=[('Hrithik',2009,8.5),('Ajay',2008,8.7),('Ramees',2007,6.8),('Shabin',2009,7.0)]

In [55]:
#creating array
arr=np.array(values, dtype=dtypes)
print("Array sorted by names:\n",np.sort(arr, order='name'))

Array sorted by names:
 [(b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5) (b'Ramees', 2007, 6.8)
 (b'Shabin', 2009, 7. )]
