In [1]:
distance=[10,15,17,26]
time=[.30,.47,.55,1.20]


In [2]:
import numpy as np #import numpy

In [3]:
np_distance=np.array(distance) #create "distance" and "time" numpy arrays
np_time=np.array(time)
speed=np_distance/np_time #mathamatical function applied over the entire "distance" and "time" array
speed #output

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [4]:
distance=[10,15,17,26]
time=[.30,.47,.55,1.20]

np_distance=np.array(distance) #create "distance" and "time" numpy arrays
np_time=np.array(time)

import numpy as np #import numpy but here the processing sequnce is diffrent so we get error
speed=np_distance/np_time
speed


array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [5]:
distance=[10,15,17,26]
time=[.30,.47,.55,1.20]

import numpy

np_distance=numpy.array(distance) #create "distance" and "time" numpy arrays
np_time=numpy.array(time)


speed=np_distance/np_time
speed


array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [6]:
import numpy as np

np_city=np.array(['NYC','LA','Miami','Houston']) #this is single dimension, ndim used to know dimn
np_city.ndim

1

In [7]:
np_city_with_state=np.array([['NYC','LA','Miami','Houston'],['NY','CA','FL','TX']])
np_city_with_state.ndim

2

In [8]:
np_city.shape

(4,)

In [9]:
np_city_with_state.shape #(no:of arrays,row,colunm)

(2, 4)

In [10]:
np_city.size #total no of elements in the array

4

In [11]:
np_city_with_state.size

8

In [12]:
np_city

array(['NYC', 'LA', 'Miami', 'Houston'], dtype='<U7')

In [13]:
np_city_with_state

array([['NYC', 'LA', 'Miami', 'Houston'],
       ['NY', 'CA', 'FL', 'TX']], dtype='<U7')

In [14]:
np_city_with_state.dtype #7 is the length of longest string

dtype('<U7')

In [15]:
#Example array operation numpy

first_trial_cyclist=[10,15,17,26] #first trial
second_trial_cyclist=[12,11,21,24] #second trial

In [16]:
np_first_trial_cyclist=np.array(first_trial_cyclist)

In [17]:
np_second_trial_cyclist=np.array(second_trial_cyclist)

In [18]:
np_first_trial_cyclist+np_second_trial_cyclist #total distance

array([22, 26, 38, 50])

In [19]:
#example accessing array elements:Indexing
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]]) #creating 2D array using cyclist trail


In [20]:
first_trial=cyclist_trials[0] #first trial data

In [21]:
first_trial 

array([10, 15, 17, 26])

In [22]:
second_trial=cyclist_trials[1] #second trial data
second_trial

array([12, 11, 21, 24])

In [23]:
#indexing for 2D array
first_cyclist_firstTrial = cyclist_trials[0][0]
first_cyclist_firstTrial

10

In [24]:
first_cyclist_all_Trials = cyclist_trials[:] # : selects entire row
first_cyclist_all_Trials

array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [25]:
first_cyclist_all_Trials = cyclist_trials[:,0] #selects all index_0 element from entire row
first_cyclist_all_Trials

array([10, 12])

In [26]:
#slicing:accessing array elements
cyclist_trials.shape

(2, 4)

In [27]:
two_cyclist_trial_data=cyclist_trials[:,1:3] #slicing array data[:,1,3] where 1 is inclusive but 3 is not

In [28]:
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

In [29]:
#iteration
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])

In [30]:
two_cyclist_trial_data=cyclist_trials[:,1:3]

In [31]:
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

In [32]:
for iterate_cyclist_trials_data in cyclist_trials: #iterate with for loop through entire dataset
    print(iterate_cyclist_trials_data)

[10 15 17 26]
[12 11 21 24]


In [33]:
for iterate_two_cyclist_trials_data in two_cyclist_trial_data: #iterate with for loop through the "two cyclist" database
    print(iterate_two_cyclist_trials_data)

[15 17]
[11 21]


In [34]:
#indexing with boolean array
test_scores = np.array([[83,71,57,63],[54,68,81,45]])

In [35]:
passing_score = test_scores>60

In [36]:
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [37]:
test_scores[passing_score]

array([83, 71, 63, 68, 81])

In [38]:
#ufunc Examples
np_sqrt = np.sqrt([2,4,9,16]) #numbers for which sqrt will be calculated

In [39]:
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

In [40]:
from numpy import pi
np.cos(0)

1.0

In [41]:
np.sin(pi/2)

1.0

In [42]:
np.cos(pi)

-1.0

In [43]:
np.floor([1.5,1.6,2.7,3.3,6.5,-1.4])

array([ 1.,  1.,  2.,  3.,  6., -2.])

In [44]:
np.exp([0,1,5]) #exponential functions for complex mathamatical calculations

array([  1.        ,   2.71828183, 148.4131591 ])

In [16]:
#Shape manipulation: Array
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [17]:
new_cyclist_trials.ravel() #Flattens the dataset

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [18]:
new_cyclist_trials.reshape(3,4) #changes or reshapes the dataset to 3 rows and 4 coloums

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [19]:
new_cyclist_trials.resize(2,6) #resizes again to 2 rows and 6 coloums

In [20]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [21]:
np.hsplit(new_cyclist_trials,2) #splits the array into two

[array([[10, 15, 17],
        [12, 11, 21]]), array([[26, 13, 19],
        [24, 14, 23]])]

In [22]:
np.vsplit(new_cyclist_trials,2)

[array([[10, 15, 17, 26, 13, 19]]), array([[12, 11, 21, 24, 14, 23]])]

In [10]:
new_cyclist_1 = np.array([10,15,17,26,13,19]) 

In [11]:
new_cyclist_2 = np.array([12,11,21,24,14,23])

In [12]:
np.hstack([new_cyclist_1,new_cyclist_2]) #Stack the arrays together horizontal stack

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [13]:
np.vstack([new_cyclist_1,new_cyclist_2]) #vertical stack

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [54]:
#Broadcasting
import numpy as np

In [55]:
array_a = np.array([2,3,5,8]) #creating array of same shape
array_b = np.array([.3,.3,.3,.3])


In [56]:
array_a * array_b #multiply arrays

array([0.6, 0.9, 1.5, 2.4])

In [57]:
scalar_c = .3 #create a variable with scalar value

In [58]:
array_a * scalar_c #multiply ID array with a scalar

array([0.6, 0.9, 1.5, 2.4])

In [61]:
#Broadcasting constraints
array_d = np.array([4,3])

In [60]:
array_a * array_d 

#when numpy operates two arrays, it compares their shapes element wise.it finds these shapes compatible only if their dimensions are the same or one of them has dimn size of 1
#if error it shows arrays have incompatible shapes

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [62]:
np_week_one = np.array([105,135,195,120,165])
np_week_two = np.array([123,156,230,200,147])

In [63]:
total_earnings = np_week_one+np_week_two #element-wise operation

In [64]:
total_earnings #total earnings for 2 wks

array([228, 291, 425, 320, 312])

In [65]:
np_week_one_hrs = np_week_one / 15 #calculate week one hrs hourly wage

In [66]:
np_week_one_hrs #no of working hrs per day in week 

array([ 7.,  9., 13.,  8., 11.])

In [67]:
#Linear Algebra Transpose
test_scores = np.array([[83,71,57,63],[54,68,81,45]])

In [68]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [69]:
matrix_array = np.array([[10,20],[15,25]])

In [70]:
np.linalg.inv(matrix_array) #inverse only work with square matrix

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [71]:
np.trace(matrix_array) #sum of diagonal elements

35

In [ ]:
dir(numpy)

In [73]:
import numpy as np
a8 = np.ones((3,3))
a8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
import numpy as np
a8 = np.zeros((3,3))
a8

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
a9 = np.full((2,3),7)
a9

array([[7, 7, 7],
       [7, 7, 7]])

In [80]:
a10 = np.eye(5)
a10

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
a11 = np.random.randn(2,2)
a11

array([[ 1.26783485, -0.60241699],
       [-1.37690947, -0.63210762]])

In [84]:
a12 = np.random.randn(2,1)
a12

array([[ 1.80895735],
       [-0.24180727]])

In [85]:
a11 = np.random.randn(3,2)
a11

array([[ 0.53192633,  0.28787728],
       [ 1.22402413,  0.24374834],
       [-0.06898526, -1.91444348]])

In [86]:
#row and column view of an array

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
row_r1 = a[0, :2] #rank 1 view of the second row of a
row_r2 = a[:1, :2] #rank 2 view of the second row of a

print(a)
print()

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 2] (2,)
[[1 2]] (1, 2)


In [89]:
#we can make the same distinction when accessing colums of an array

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  #prints as an array
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [93]:
a = np.array([[10,20,30],[44,55,66],[27,28,29],[40,41,42]])
#rint(a)

b = np.array([0,2,0,1]) #takes one value from (0,0) (1,2) (2,0) (3,1) dfdf344gdfff55rrdff
print(a[np.arange(4),b])
print(a)

[10 66 27 41]
[[10 20 30]
 [44 55 66]
 [27 28 29]
 [40 41 42]]


# file handling

In [95]:
#example for reading and writing array on the file

a = np.array(['a','b','c'])
np.save('indu.npy',a)
b = np.load('indu.npy')
print(b)

['a' 'b' 'c']


In [96]:
a = np.array(range(8))
np.savetxt('Numpy03.txt',a)
b = np.loadtxt('numpy03.txt')
print(b)

[0. 1. 2. 3. 4. 5. 6. 7.]


# Array Handling


1.assingnment
2.View
3.Copy


In [4]:
#simple assignment: can change both value and shape
import numpy as np
a = np.array(range(6))
print("Array : a",a)
print(),

print("a is assigned to b:" )
b=a
print(b)
print()

print("check equality of a & b's memory location") #memory location is same
print("a is b :",a is b);print() #is for memory location

print("change shape of b: ")
b.shape = (3,2)
print(b);print()
print("shape of a also changed: ")
print(a);print()

print("change value of a")
a[:]=10
print("a array: ");print(a);print()
print("b value also changed :");print(b)

Array : a [0 1 2 3 4 5]

a is assigned to b:
[0 1 2 3 4 5]

check equality of a & b's memory location
a is b : True

change shape of b: 
[[0 1]
 [2 3]
 [4 5]]

shape of a also changed: 
[[0 1]
 [2 3]
 [4 5]]

change value of a
a array: 
[[10 10]
 [10 10]
 [10 10]]

b value also changed :
[[10 10]
 [10 10]
 [10 10]]


In [6]:
#view/shallow copy
#can change only data not shape and memory location

a = np.array(range(6))
print("Array : a",a)
print(),

print("a's  view is b:" )
b=a.view()
print(b)
print()

print("check equality of a & b's memory location") #memory location is not same
print("a is b :",a is b);print() #is for memory location

print("change shape of b: ")
b.shape = (3,2)
print(b);print()
print("shape of a did not changed: ")
print(a);print()

print("change value of a")
a[:]=10
print("a array: ");print(a);print()
print("b value also changed :");print(b)

Array : a [0 1 2 3 4 5]

a's  view is b:
[0 1 2 3 4 5]

check equality of a & b's memory location
a is b : False

change shape of b: 
[[0 1]
 [2 3]
 [4 5]]

shape of a did not changed: 
[0 1 2 3 4 5]

change value of a
a array: 
[10 10 10 10 10 10]

b value also changed :
[[10 10]
 [10 10]
 [10 10]]


In [8]:
#Copy/Deep Copy
#diff memory location do not change value and shape

a = np.array(range(6))
print("Array : a",a)
print(),

print("a's  view is b:" )
b=a.copy()
print(b)
print()

print("check equality of a & b's memory location") #memory location is not same
print("a is b :",a is b);print()

print("change shape of b: ")
b.shape = (3,2)
print(b);print()
print("shape of a did not changed: ")
print(a);print()

print("change value of a")
a[:]=10
print("a array: ");print(a);print()
print("b value will not change :");print(b)

Array : a [0 1 2 3 4 5]

a's  view is b:
[0 1 2 3 4 5]

check equality of a & b's memory location
a is b : False

change shape of b: 
[[0 1]
 [2 3]
 [4 5]]

shape of a did not changed: 
[0 1 2 3 4 5]

change value of a
a array: 
[10 10 10 10 10 10]

b value will not change :
[[0 1]
 [2 3]
 [4 5]]
